### ISSUE TITLE
Changing guilds doesn't update member list on desktop

### ISSUE THREAD

**Issue by 2t34lth** [OpenBonfire/bonfire#1]
When you change guilds on desktop, the member list doesn't update for guilds that were previously visited.
Platform: Linux
Version: Latest commit (50e161c1fa6b3ea7cc4fcb1ed28a89cf2b74199e)

**Comment by EricApostal** [comment]
Thanks for reporting this @2t34lth ! I am aware of this issue, I'm just super bad at tracking it. The issue stems with how I'm handling guild subscriptions. Discord doesn't give new data back every time you subscribe to a channel, and I'm not handling that properly. I'll do some more research on how it's intended to be handled and get back when I find something.

**Comment by EricApostal** [comment]
@2t34lth Should be fixed! Please give the actions build a go when it's ready.

**Comment by EricApostal** [comment]
@2t34lth I created a new issue so it's easier to track, which also contains a temporary fix (as I've also had this issue local on Fedora 40) https://github.com/OpenBonfire/bonfire/issues/3
